using LearnOpenGL.OpenTK.Core;

namespace LearnOpenGL.OpenTK.Demos;

public static class DemoRegistry
{
    private static readonly SortedDictionary<string, Func<RunOptions, DemoWindow>> Factories = new(StringComparer.OrdinalIgnoreCase)
    {
        ["1.getting_started/1.1.hello_window"] = options => new ClearColorDemo(options, clear: false),
        ["1.getting_started/1.2.hello_window_clear"] = options => new ClearColorDemo(options, clear: true),
        ["1.getting_started/2.1.hello_triangle"] = options => new TriangleDemo(options, TriangleVariant.Single),
        ["1.getting_started/2.2.hello_triangle_indexed"] = options => new TriangleDemo(options, TriangleVariant.IndexedRectangle),
        ["1.getting_started/2.3.hello_triangle_exercise1"] = options => new TriangleDemo(options, TriangleVariant.TwoTriangles),
        ["1.getting_started/2.4.hello_triangle_exercise2"] = options => new TriangleDemo(options, TriangleVariant.TwoSeparateTriangles),
        ["1.getting_started/2.5.hello_triangle_exercise3"] = options => new TriangleDemo(options, TriangleVariant.TwoColoredTriangles),
        ["1.getting_started/3.1.shaders_uniform"] = options => new ShaderTriangleDemo(options, ShaderTriangleVariant.Uniform),
        ["1.getting_started/3.2.shaders_interpolation"] = options => new ShaderTriangleDemo(options, ShaderTriangleVariant.Interpolation),
        ["1.getting_started/3.3.shaders_class"] = options => new ShaderTriangleDemo(options, ShaderTriangleVariant.ClassShader),
        ["1.getting_started/3.4.shaders_exercise1"] = options => new ShaderTriangleDemo(options, ShaderTriangleVariant.UpsideDown),
        ["1.getting_started/3.5.shaders_exercise2"] = options => new ShaderTriangleDemo(options, ShaderTriangleVariant.OffsetRight),
        ["1.getting_started/3.6.shaders_exercise3"] = options => new ShaderTriangleDemo(options, ShaderTriangleVariant.PositionColor),
        ["1.getting_started/4.1.textures"] = options => new TextureRectangleDemo(options, TextureRectangleVariant.SingleTexture),
        ["1.getting_started/4.2.textures_combined"] = options => new TextureRectangleDemo(options, TextureRectangleVariant.CombinedTextures),
        ["1.getting_started/4.3.textures_exercise1"] = options => new TextureRectangleDemo(options, TextureRectangleVariant.FaceMirrorInShader),
        ["1.getting_started/4.4.textures_exercise2"] = options => new TextureRectangleDemo(options, TextureRectangleVariant.FaceFlipped),
        ["1.getting_started/4.5.textures_exercise3"] = options => new TextureRectangleDemo(options, TextureRectangleVariant.OffsetCoordinates),
        ["1.getting_started/4.6.textures_exercise4"] = options => new TextureRectangleDemo(options, TextureRectangleVariant.MixControlled),
        ["1.getting_started/5.1.transformations"] = options => new TransformationsDemo(options, TransformVariant.Primary),
        ["1.getting_started/5.2.transformations_exercise1"] = options => new TransformationsDemo(options, TransformVariant.ReversedOrder),
        ["1.getting_started/5.2.transformations_exercise2"] = options => new TransformationsDemo(options, TransformVariant.TwoContainers),
        ["1.getting_started/6.1.coordinate_systems"] = options => new CoordinateSystemsDemo(options, CoordinateVariant.SingleCube),
        ["1.getting_started/6.2.coordinate_systems_depth"] = options => new CoordinateSystemsDemo(options, CoordinateVariant.DepthCube),
        ["1.getting_started/6.3.coordinate_systems_multiple"] = options => new CoordinateSystemsDemo(options, CoordinateVariant.MultipleCubes),
        ["1.getting_started/6.4.coordinate_systems_exercise3"] = options => new CoordinateSystemsDemo(options, CoordinateVariant.AnimatedEveryThirdCube),
        ["1.getting_started/7.1.camera_circle"] = options => new CameraDemo(options, CameraVariant.Circle),
        ["1.getting_started/7.2.camera_keyboard_dt"] = options => new CameraDemo(options, CameraVariant.Keyboard),
        ["1.getting_started/7.3.camera_mouse_zoom"] = options => new CameraDemo(options, CameraVariant.MouseZoom),
        ["1.getting_started/7.4.camera_class"] = options => new CameraDemo(options, CameraVariant.ClassCamera),
        ["1.getting_started/7.5.camera_exercise1"] = options => new CameraDemo(options, CameraVariant.GroundLocked),
        ["1.getting_started/7.6.camera_exercise2"] = options => new CameraDemo(options, CameraVariant.CustomLookAt),
        ["2.lighting/1.colors"] = options => new LightingDemo(options, LightingVariant.Colors),
        ["2.lighting/2.1.basic_lighting_diffuse"] = options => new LightingDemo(options, LightingVariant.Diffuse),
        ["2.lighting/2.2.basic_lighting_specular"] = options => new LightingDemo(options, LightingVariant.Specular),
        ["2.lighting/2.3.basic_lighting_exercise1"] = options => new LightingDemo(options, LightingVariant.MovingLight),
        ["2.lighting/2.4.basic_lighting_exercise2"] = options => new LightingDemo(options, LightingVariant.ViewSpaceLighting),
        ["2.lighting/2.5.basic_lighting_exercise3"] = options => new LightingDemo(options, LightingVariant.Gouraud),
        ["2.lighting/3.1.materials"] = options => new LightingDemo(options, LightingVariant.Materials),
        ["2.lighting/3.2.materials_exercise1"] = options => new LightingDemo(options, LightingVariant.MaterialsExercise1),
        ["2.lighting/4.1.lighting_maps_diffuse_map"] = options => new LightingDemo(options, LightingVariant.DiffuseMap),
        ["2.lighting/4.2.lighting_maps_specular_map"] = options => new LightingDemo(options, LightingVariant.SpecularMap),
        ["2.lighting/4.3.lighting_maps_exercise2"] = options => new LightingDemo(options, LightingVariant.InvertedSpecularMap),
        ["2.lighting/4.4.lighting_maps_exercise4"] = options => new LightingDemo(options, LightingVariant.EmissionMap),
        ["2.lighting/5.1.light_casters_directional"] = options => new LightingDemo(options, LightingVariant.DirectionalLight),
        ["2.lighting/5.2.light_casters_point"] = options => new LightingDemo(options, LightingVariant.PointLight),
        ["2.lighting/5.3.light_casters_spot"] = options => new LightingDemo(options, LightingVariant.SpotLight),
        ["2.lighting/5.4.light_casters_spot_soft"] = options => new LightingDemo(options, LightingVariant.SoftSpotLight),
        ["2.lighting/6.multiple_lights"] = options => new LightingDemo(options, LightingVariant.MultipleLights),
        ["2.lighting/6.multiple_lights_exercise1"] = options => new LightingDemo(options, LightingVariant.MultipleLightsDesert),
        ["3.model_loading/1.model_loading"] = options => new ModelLoadingDemo(options),
        ["4.advanced_opengl/1.1.depth_testing"] = options => new AdvancedOpenGlDemo(options, AdvancedOpenGlVariant.DepthTesting),
        ["4.advanced_opengl/1.2.depth_testing_view"] = options => new AdvancedOpenGlDemo(options, AdvancedOpenGlVariant.DepthTestingView),
        ["4.advanced_opengl/2.stencil_testing"] = options => new AdvancedOpenGlDemo(options, AdvancedOpenGlVariant.StencilTesting),
        ["4.advanced_opengl/3.1.blending_discard"] = options => new AdvancedOpenGlDemo(options, AdvancedOpenGlVariant.BlendingDiscard),
        ["4.advanced_opengl/3.2.blending_sort"] = options => new AdvancedOpenGlDemo(options, AdvancedOpenGlVariant.BlendingSort),
        ["4.advanced_opengl/4.face_culling_exercise1"] = options => new AdvancedOpenGlDemo(options, AdvancedOpenGlVariant.FaceCullingExercise),
        ["4.advanced_opengl/5.1.framebuffers"] = options => new AdvancedOpenGlDemo(options, AdvancedOpenGlVariant.Framebuffers),
        ["4.advanced_opengl/5.2.framebuffers_exercise1"] = options => new AdvancedOpenGlDemo(options, AdvancedOpenGlVariant.FramebuffersExercise1),
        ["4.advanced_opengl/6.1.cubemaps_skybox"] = options => new CubemapDemo(options, CubemapVariant.Skybox),
        ["4.advanced_opengl/6.2.cubemaps_environment_mapping"] = options => new CubemapDemo(options, CubemapVariant.EnvironmentMapping),
        ["4.advanced_opengl/8.advanced_glsl_ubo"] = options => new AdvancedGlslUboDemo(options),
        ["4.advanced_opengl/9.1.geometry_shader_houses"] = options => new GeometryShaderHousesDemo(options),
        ["4.advanced_opengl/9.2.geometry_shader_exploding"] = options => new ModelGeometryDemo(options, ModelGeometryVariant.Exploding),
        ["4.advanced_opengl/9.3.geometry_shader_normals"] = options => new ModelGeometryDemo(options, ModelGeometryVariant.Normals),
        ["4.advanced_opengl/10.1.instancing_quads"] = options => new InstancingQuadsDemo(options),
        ["4.advanced_opengl/10.2.asteroids"] = options => new AsteroidsDemo(options, AsteroidsVariant.ManyDrawCalls),
        ["4.advanced_opengl/10.3.asteroids_instanced"] = options => new AsteroidsDemo(options, AsteroidsVariant.Instanced),
        ["4.advanced_opengl/11.1.anti_aliasing_msaa"] = options => new AntiAliasingDemo(options, AntiAliasingVariant.Msaa),
        ["4.advanced_opengl/11.2.anti_aliasing_offscreen"] = options => new AntiAliasingDemo(options, AntiAliasingVariant.Offscreen),
        ["5.advanced_lighting/1.advanced_lighting"] = options => new AdvancedLightingDemo(options, AdvancedLightingVariant.AdvancedLighting),
        ["5.advanced_lighting/2.gamma_correction"] = options => new AdvancedLightingDemo(options, AdvancedLightingVariant.GammaCorrection),
        ["5.advanced_lighting/3.1.1.shadow_mapping_depth"] = options => new ShadowMappingDemo(options, ShadowMappingVariant.DepthOnly),
        ["5.advanced_lighting/3.1.2.shadow_mapping_base"] = options => new ShadowMappingDemo(options, ShadowMappingVariant.Base),
        ["5.advanced_lighting/3.1.3.shadow_mapping"] = options => new ShadowMappingDemo(options, ShadowMappingVariant.Complete),
        ["5.advanced_lighting/3.2.1.point_shadows"] = options => new PointShadowsDemo(options, PointShadowsVariant.Hard),
        ["5.advanced_lighting/3.2.2.point_shadows_soft"] = options => new PointShadowsDemo(options, PointShadowsVariant.Soft),
        ["5.advanced_lighting/3.3.csm"] = options => new CsmLegacyDepthDemo(options),
        ["5.advanced_lighting/4.normal_mapping"] = options => new AdvancedLightingDemo(options, AdvancedLightingVariant.NormalMapping),
        ["5.advanced_lighting/5.1.parallax_mapping"] = options => new AdvancedLightingDemo(options, AdvancedLightingVariant.ParallaxMapping),
        ["5.advanced_lighting/5.2.steep_parallax_mapping"] = options => new AdvancedLightingDemo(options, AdvancedLightingVariant.SteepParallaxMapping),
        ["5.advanced_lighting/5.3.parallax_occlusion_mapping"] = options => new AdvancedLightingDemo(options, AdvancedLightingVariant.ParallaxOcclusionMapping),
        ["5.advanced_lighting/6.hdr"] = options => new HdrBloomDemo(options, HdrBloomVariant.Hdr),
        ["5.advanced_lighting/7.bloom"] = options => new HdrBloomDemo(options, HdrBloomVariant.Bloom),
        ["5.advanced_lighting/8.1.deferred_shading"] = options => new DeferredShadingDemo(options, DeferredVariant.Shading),
        ["5.advanced_lighting/8.2.deferred_shading_volumes"] = options => new DeferredShadingDemo(options, DeferredVariant.Volumes),
        ["5.advanced_lighting/9.ssao"] = options => new SsaoDemo(options),
        ["6.pbr/1.1.lighting"] = options => new PbrLightingDemo(options, PbrLightingVariant.ScalarMaterial),
        ["6.pbr/1.2.lighting_textured"] = options => new PbrLightingDemo(options, PbrLightingVariant.TexturedMaterial),
        ["6.pbr/2.1.1.ibl_irradiance_conversion"] = options => new PbrIblDemo(options, PbrIblVariant.IrradianceConversion),
        ["6.pbr/2.1.2.ibl_irradiance"] = options => new PbrIblDemo(options, PbrIblVariant.Irradiance),
        ["6.pbr/2.2.1.ibl_specular"] = options => new PbrIblDemo(options, PbrIblVariant.Specular),
        ["6.pbr/2.2.2.ibl_specular_textured"] = options => new PbrIblDemo(options, PbrIblVariant.SpecularTextured),
        ["7.in_practice/1.debugging"] = options => new DebuggingDemo(options),
        ["7.in_practice/2.text_rendering"] = options => new TextRenderingDemo(options),
        ["7.in_practice/3.2d_game"] = options => new BreakoutDemo(options, 9),
        ["7.in_practice/3.2d_game/0.full_source"] = options => new BreakoutDemo(options, 9),
        ["7.in_practice/3.2d_game/0.full_source/progress"] = options => new BreakoutDemo(options, 9),
        ["7.in_practice/3.2d_game/0.full_source/progress/2.program"] = options => new BreakoutDemo(options, 1),
        ["7.in_practice/3.2d_game/0.full_source/progress/2.game"] = options => new BreakoutDemo(options, 2),
        ["7.in_practice/3.2d_game/0.full_source/progress/3.game"] = options => new BreakoutDemo(options, 3),
        ["7.in_practice/3.2d_game/0.full_source/progress/4.game"] = options => new BreakoutDemo(options, 4),
        ["7.in_practice/3.2d_game/0.full_source/progress/5.game"] = options => new BreakoutDemo(options, 5),
        ["7.in_practice/3.2d_game/0.full_source/progress/5.1.ball_object_collisions"] = options => new BreakoutDemo(options, 5),
        ["7.in_practice/3.2d_game/0.full_source/progress/6.game"] = options => new BreakoutDemo(options, 6),
        ["7.in_practice/3.2d_game/0.full_source/progress/7.game"] = options => new BreakoutDemo(options, 7),
        ["7.in_practice/3.2d_game/0.full_source/progress/8.game"] = options => new BreakoutDemo(options, 8),
        ["7.in_practice/3.2d_game/0.full_source/progress/9.game"] = options => new BreakoutDemo(options, 9),
        ["8.guest/2020/oit"] = options => new GuestShowcaseDemo(options, GuestShowcaseVariant.WeightedOit),
        ["8.guest/2020/skeletal_animation"] = options => new GuestShowcaseDemo(options, GuestShowcaseVariant.SkeletalAnimation),
        ["8.guest/2021/1.scene/1.scene_graph"] = options => new GuestShowcaseDemo(options, GuestShowcaseVariant.SceneGraph),
        ["8.guest/2021/1.scene/2.frustum_culling"] = options => new GuestShowcaseDemo(options, GuestShowcaseVariant.FrustumCulling),
        ["8.guest/2021/2.csm"] = options => new GuestShowcaseDemo(options, GuestShowcaseVariant.Csm),
        ["8.guest/2021/3.tessellation/terrain_gpu_dist"] = options => new GuestShowcaseDemo(options, GuestShowcaseVariant.TerrainGpu),
        ["8.guest/2021/3.tessellation/terrain_cpu_src"] = options => new GuestShowcaseDemo(options, GuestShowcaseVariant.TerrainCpu),
        ["8.guest/2021/4.dsa"] = options => new DsaTriangleDemo(options),
        ["8.guest/2022/5.computeshader_helloworld"] = options => new ComputeShaderHelloWorldDemo(options),
        ["8.guest/2022/6.physically_based_bloom"] = options => new GuestShowcaseDemo(options, GuestShowcaseVariant.PhysicallyBasedBloom),
        ["8.guest/2022/7.area_lights/1.area_light"] = options => new GuestShowcaseDemo(options, GuestShowcaseVariant.AreaLight),
        ["8.guest/2022/7.area_lights/2.multiple_area_lights"] = options => new GuestShowcaseDemo(options, GuestShowcaseVariant.MultipleAreaLights),
    };

    public static IEnumerable<string> Ids => Factories.Keys;

    public static bool TryCreate(string id, RunOptions options, out DemoWindow window)
    {
        if (Factories.TryGetValue(id.Replace('\\', '/'), out var factory))
        {
            window = factory(options);
            return true;
        }

        window = null!;
        return false;
    }
}
